### ISSUE TITLE
Request easier way to adjust overall disk size

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-bigip-image-generator#14]
**Is your feature request related to a problem? Please describe.**
I ran image builder and it seems to default to a 9GB disk size. From reading the docs, it appears I have to update the LV sizes which will update the overall disk size. Is this the only way? 

**Describe the solution you'd like**
When I run the build tool it automatically knows I'm running a 1boot option LTM option, and therefore, 40GB size for example.

**Additional context**
config.yml
```
GCE_BUCKET: "mybucket123"
GOOGLE_APPLICATION_CREDENTIALS: "svc-acct.json"
```

execution command
```
./build-image -i ../f5-images/BIGIP-13.1.3.3-0.0.6.iso -c config.yml -p gce -m ltm -b 1
```

**Output snippet
```
BIG-IP Disk Size =9
Creating 9G disk '/home/admin/f5-bigip-image-generator/src/lib/bash/../../../artifacts/BIGIP-13.1.3.3-0.0.6/gce/ltm_1slot/disk.raw' in format 'raw' -- start time: 01:57:44
Formatting '/home/admin/f5-bigip-image-generator/src/lib/bash/../../../artifacts/BIGIP-13.1.3.3-0.0.6/gce/ltm_1slot/disk.raw', fmt=raw size=9663676416
Creating 9G disk '/home/admin/f5-bigip-image-generator/src/lib/bash/../../../artifacts/BIGIP-13.1.3.3-0.0.6/gce/ltm_1slot/disk.raw' in format 'raw' -- elapsed time: 0:00:00
Wrote create_raw_disk status to '/home/admin/f5-bigip-image-generator/src/lib/bash/../../../artifacts/BIGIP-13.1.3.3-0.0.6/gce/ltm_1slot/create_raw_disk.json'.
```

**Comment by JeffGiroux** [comment]
Adding this to your config.yml will result in a 72GB disk size:
```
UPDATE_LV_SIZES: >-
  {
    "appdata": 32000,
    "config": 3500,
    "log": 4500,
    "shared": 22000,
    "var": 5500
  }
```

**Comment by kmaloney** [comment]
The images created by the image generator follow the model used for images available on downloads.f5.com.  The initial problem that the image generator is trying to solve is to give users the ability to create similar, representative images for a hypervisor or cloud when they may not be available such as an engineering hotfix.  These image sizes were selected after reviewing numerous customer configuration deployment based on customer requests for smaller images that optimize resource usage.  

For each platform, there are four images that are a combination of MODULES and BOOT_LOCATIONS (e.g. LTM/LTM_1SLOT/ALL/ALL_1SLOT).  The MODULES for an image can be LTM or ALL.  LTM images are for smaller deployments (typically 1 licensed module), and ALL images are for larger deployments (2 or more licensed modules).  BOOT_LOCATIONS indicates how many boot locations (or slots) where BIG-IP software can be installed.  There are either one or two BOOT_LOCATIONS.  For instances where upgrades will not be performed, one boot location is sufficient.  If you intend to perform upgrades, then two BOOT_LOCATIONS are needed.

There are two configuration items to adjust image size at a macro level: MODULES and BOOT_LOCATIONS.    The UPDATE_LV_SIZES configuration item intended to do modifications to limited number of logical volumes.  

Are you trying to mimic the size of an image on downloads.f5.com?  That is, do the MODULES and BOOT_LOCATION configuration items provide the adjustments that you are looking for?  If so, we can enhance the documentation to clarify this.  Or does your second comment indicate that you determined how to create an image with the desired size via UPDATE_LV_SIZES?

**Comment by JeffGiroux** [comment]
My use case was simple at first. I wanted to simply upload an image to Google. Our F5 downloads folder has Azure and AWS folders for images but not one for Google. So, I grabbed an ISO for F5 image builder to rebuild (no other magic, no other injections or EHF), then had it upload to Google.

The documentation did not specify sizing. I used the yml and build CLI command as noted in the opening of the ticket, and this resulted in a 9GB drive.  "-m ltm -b 1"

My expected results:
Download ISO, run it through image generator, use github README steps to learn how to build image. Expectation is that if I choose LTM, 1 boot that I get a 40-50GB size. If I choose all modules, then this should be affected dynamically.

Current behavior:
It seems I have to update LV sizes. 

Based on what you're saying, I should be able to adjust modules and/or boot_locations and this will affect image size? If so, what is the guidance in doing that and what is the expected output disk size for your example?

I'm a little lost now due to gaps in the docs like a full-blown quick start. There's lots of sporadic pieces of info. To install into Google, I had to read the main README, then hop over to the google page, then hop back. I'm hoping to see a nice summarized quickstart with example config.yml that show different sizings, different cloud providers, etc. I see docs on F5 clouddocs, but those simply point to github.

**Comment by kmaloney** [comment]
Because the goal of the image generator is to create images similar to the official BIG-IP VE images, the MODULES/BOOT_LOCATIONS settings follow the pattern established for official BIG-IP VE images.  This KB article has a detailed explanation of the images sizes as well as the descriptions of the different "template type" (e.g. "ALL_1SLOT")  https://support.f5.com/csp/article/K14946

I get your point.  The documentation is making a leap that all users are aware of the BIG-IP VE image model.  We can add documentation that leverages this detailed information to better guide users regarding the required sizing parameters.

**Comment by JeffGiroux** [comment]
That chart helps. Thx, I forgot about that and how ltm-1slot could be 9GB...explains why my image without UPDATE_LV_SIZES defaulted to 9GB with ltm and 1slot argument flags. Glad it wasn't something that I was doing wrong.

Agree, documentation could help clear it up. A reference to the KB maybe. Or a table that shows the same. Maybe example config.yml + build command lines and various flags with the different resulting image sizes would help. That way, if config.yml contains xyz, modules xyz, boot x, then image size will be X.

**Comment by kmaloney** [comment]
Tracking documentation issue with Jira item VECLOUD-973.

**Comment by kmaloney** [comment]
Documentation has been updated to address this issue.
