### ISSUE TITLE
AWS snapshot description / tagging

### ISSUE THREAD

**Issue by amolari** [f5devcentral/f5-bigip-image-generator#15]
**Is your feature request related to a problem? Please describe.**
Not easy to match the EC2 snapshots (created by the vm-import operation) with the custom AMIs

**Describe the solution you'd like**
Please add the context (custom AMI name for example) in the snapshot description and/or tag the snapshot. Goal is to be able to locate snapshots associated with a specific custom AMI.

**Additional context**
At this time (v1.5), the snapshots do have such a description: 

> Created by AWS-VMImport service for import-snap-0041568aab14529ee

They are not tagged.
When the number of custom AMIs  increase and we delete some of them, we want to delete the associated snapshots too.

**Comment by kmaloney** [comment]
This issue is being tracked internally with Jira story VECLOUD-983.

**Comment by kmaloney** [comment]
FYI - Tagging snapshots is straightforward.  However, it appears that AWS is not honoring the description setting, and it can't be edited after the fact.  As a result, the API limits the fix to snapshot tagging.

**Comment by kmaloney** [comment]
Resolved in v1.6.  As noted above, snapshot description was added in the payload, but the AWS API is currently not using it.  Snapshot tagging does work.
