### ISSUE TITLE
Cloud images should be able to be generated locally 

### ISSUE THREAD

**Issue by Klipope** [f5devcentral/f5-bigip-image-generator#23]
Problem: 
due to segregation of duty, it is possible that the team/person who generates the custom BIG-IP image does not have the access key and secret to upload it automatically to the desired cloud platform. as of today (and unless I am mistaking) it is therefore not possible to use the -p option of the tool and this could cause some issues in terms of appropriate settings being applied to the image (like for example in our case the datsource_list option for Alibaba). 

Solution: 
be able to generate the cloud image locally with all predefined settings for the specified cloud provider. 
the image would then be handed over "manually" to the team in charge of uploads to the cloud bucket.

**Comment by kmaloney** [comment]
That is a scenario that we didn't account for, but it seems like it could be a common usage.  We will track this internally via Jira VECLOUD-1198.  

Workaround:

There are subtle differences in the virtual disk images based on the platform like hypervisor type (unique to each cloud environment).  An Alibaba virtual disk image will behave slightly differently than a basic qcow2 virtual disk image.  So, you are best off building an Alibaba virtual disk image if that is the target cloud.

I realize that it isn't a great workflow, but you can run the command with "-p alibaba" and provide placeholder config vars for the Alibaba config vars to get past the basic configuration variable validation.  This will generate the Alibaba virtual disk image, but it will fail on the upload.  Nonetheless, the virtual disk image will have been created.  I wouldn't consider this a long-term solution, but it will work for now.

**Comment by kmaloney** [comment]
A new NO_UPLOAD configuration variable was added in version 1.13.  The command line option is "--no-upload".  This option will create the cloud image without uploading it to the cloud.
