### ISSUE TITLE
setup-build-env: support of web proxy

### ISSUE THREAD

**Issue by amolari** [f5devcentral/f5-bigip-image-generator#26]
**Is your feature request related to a problem? Please describe.**
In the AWS account where we have the instance, no Internet access is possible without going through a web proxy.
Defining the proxy environment variables HTTP_PROXY, HTTPS_PROXY (and lowercase variant) is not sufficient to be able to run the setup for upgrades. We had to modify some part of the code, where the python/pip installs are performed, as those programs do not support the HTTP_PROXY (and variants) environment variables

**Describe the solution you'd like**
when setup-build-env is run, detect if HTTP_PROXY is set. If yes, take its value and run the python+pip commands with proxy option using that same value.

**Additional context**

**Comment by kmaloney** [comment]
This issue is being tracked internally with VECLOUD-1264.

**Comment by kmaloney** [comment]
I haven't been able to reproduce this in AWS on newer versions of the Image Generator setup script, but I do not doubt that you are seeing this behavior.  Can you provide more information about your environment such as OS version and the version of Image Generator? 

To create the web proxy I am using [an AWS CFT](https://aws.amazon.com/blogs/security/how-to-set-up-an-outbound-vpc-proxy-with-domain-whitelisting-and-content-filtering/).  Outbound connections limited to ".amazonaws.com, .debian.org, .ubuntu.com, .python.org, .pypi.org, files.pythonhosted.org, packages.cloud.google.com".  This solution uses two private subnets (isolated on a route table without IGW access) and two public subnets (with IGW access).  Behavior confirmed using "curl -k" to try urls that should have access and others that should be denied.

I have tried reproducing the issue in AWS on an instance launched on a private subnet from a standard "Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0747bdcabd34c712a (64-bit x86)".  I use a bastion instance on the public subnet to access the Image Generator instance on the private subnet (with a restrictive SG allowing only connections from the bastion instance).

After launching the Image Generator instance, I confirm that apt/pip installs fail from the command line without configuring access to the proxy.  I set http/https proxy values in /etc/apt/apt.conf.d/proxy.conf and export http_proxy and https_proxy environment variables (lowercase only). I then "curl -k" a few urls to confirm proxy behavior and run "sudo apt update" to confirm the proxy is hooked into apt. Then I run the setup script.

**Comment by amolari** [comment]
@kmaloney I tried again with the last version (1.13) and that did work. Env variable http_proxy/https_proxy set were sufficient.
I had then an issue with the untrusted proxy ssl certificate but I could work it around appending it to the venv certifi ca file.

**Comment by kmaloney** [comment]
Thanks for confirming this.
