### ISSUE TITLE
AWS temporary credentials not working

### ISSUE THREAD

**Issue by mikeoleary** [f5devcentral/f5-bigip-image-generator#28]
**Describe the bug**
Please advise if this is a bug or by design:

We have found that when we follow the documentation using a static IAM user with an AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, the process works as expected. However, not with temporary credentials. Our corporate policy requires us to generate temporary programmatic credentials (logging on via myapplications.microsoft.com) instead of creating IAM users. Temp credentials has 3 env vars to use: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN 

It appears that if we use temp credentials, even when we supply the AWS_SESSION_TOKEN env var, we get an error when the tool attempts to upload the image to S3:
```The AWS Access Key Id you provided does not exist in our records.```

It appears as though the image is generated but not uploaded to S3 or imported as an EC2 image.

**To Reproduce**
Run through image generation and upload process, using [temporary programmatic credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html) from AWS. 

**Expected behavior**
I would expect programmatic credentials to work, whether they are temporary or permanent.

**Additional context**
N/A

**Comment by kmaloney** [comment]
I have been able to reproduce this issue and it will be tracked internally as VECLOUD-1250.

The constructor for the boto3 Session object used for AWS image generation has an aws_session_token argument that we don't currently populate.  

The solution to this will be to add a AWS_SESSION_TOKEN configuration variable (parameter) and then pass that to the boto3 Session object.

**Comment by mikeoleary** [comment]
Great to hear @kmaloney. I will be able to use iam user creds provided by our help desk until then. Thank you.

**Comment by kmaloney** [comment]
Resolved in v1.15.  Documentation has been updated.

**Comment by curtkersey** [comment]
I tested today (27 Sept 2021) with v1.15, and the temporary AWS credentials worked - thanks for your help!

**Comment by kmaloney** [comment]
> I tested today (27 Sept 2021) with v1.15, and the temporary AWS credentials worked - thanks for your help!

Thanks for the confirmation.
