### ISSUE TITLE
Is there a way to wait longer for import of snapshot?

### ISSUE THREAD

**Issue by curtkersey** [f5devcentral/f5-bigip-image-generator#29]
**Describe the bug**
I am building an image for AWS.  The ubuntu 18.04 host runs the docker container.  All is good until I get to the error:

TaskId for the import_snapshot() operation  => [import-snap-0324ba36915dd67c3]
Waiting for the import snapshot task [import-snap-0324ba36915dd67c3] to complete.
........................................................................................................................
import_snapshot_task [import-snap-0324ba36915dd67c3] didn't complete after checking [120] times!

It looks like the build-image script is waiting for 120 cycles before it gives up.  No other error is visible in the output or log file. 

**To Reproduce**

Built an image, and the script was importing the snapshot to AWS when it gave up.

**Expected behavior**
It would be good to know if there is a way to extend the time to wait longer?  I don't see any documented options for that.

**Additional context**

**Comment by kmaloney** [comment]
There is an internal configuration variable AWS_IMPORT_SNAPSHOT_TASK_RETRY_COUNT defined in src/resource/vars/aws_vars.yml that controls this behavior.

This variable is marked as internal.  I confirmed that this is not configurable by trying to build an AWS image with the configuration variable in my configuration.  This message was in the log file.

`[2021/08/03 13:42:53]-[_config_set_user_value]-[INFO] Configuration key [AWS_IMPORT_SNAPSHOT_TASK_RETRY_COUNT] is not configurable for platform [aws]!  Skipping.`

As currently implemented, you would need to alter the default value in src/resource/vars/aws_vars.yml and then rebuild the docker image.

**Comment by curtkersey** [comment]
Ok, thanks.  Looks like my error is elsewhere -- I am getting a 403 forbidden error when the snapshot is importing.  I thought I had permissions set correctly, but I am going to look at that.  I think you can close this issue for now.
