### ISSUE TITLE
Allow to install updated open-vm-tools rpm packages

### ISSUE THREAD

**Issue by alonsocamaro** [f5devcentral/f5-bigip-image-generator#30]
**Is your feature request related to a problem? Please describe.**

This RFE would allow the customer to upgrade open-vm-tools used in VMware platforms. This is needed since customers need up to date versions of open-vm-tools that are not available in the default images.

**Describe the solution you'd like**

Install the rpm before the image is built so on boot the VE is already using the updated version.

**Comment by delgadillo22** [comment]
Reviewed with engineering and concluded this is out of scope for the Image Generator based on BIG-IP's architecture / implementation as specific open-vm-tools patching is required.
