### ISSUE TITLE
Create a HOW-TO or other simple step-by-step instructional document for configuring and using image-generator

### ISSUE THREAD

**Issue by jessed** [f5devcentral/f5-bigip-image-generator#36]
The image-generator documentation is difficult to follow end-to-end. It describes the various requirements and configuration, but requires that the user put all of these pieces together to create a working solution. For the first-time user this is a very steep learning curve that would be alleviated by a series of step-by-step instructions showing the whole process from start to finish. 

This request is meant to ease the use of image-generator for the first-time user. Subsequent deployments are far easier due to having either a) already built the environment, or b) already knowing how it all fits together. HOW-TO guides excel at this type of simplification.

**Comment by kmaloney** [comment]
This issue is being tracked internally with VECLOUD-1286.

**Comment by gabetellier** [comment]
The v1.17 documentation has QSGs for each cloud:
[Alibaba](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/alibaba) - consult the [Alibaba Quick Start Guide](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/alibaba#create-image-for-alibaba-using-docker-container).
[AWS](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/aws) - consult the [AWS Quick Start Guide](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/aws#create-image-for-aws-using-docker-container).
[Azure](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/azure) - consult the [Azure Quick Start Guide](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/azure#create-image-for-azure-using-docker-container).
[GCE ](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/gce)- consult the [Google Quick Start Guide](https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/gce#create-image-for-gce-using-docker-container).
