### ISSUE TITLE
Bad links in "AWS Quick Start Guide"

### ISSUE THREAD

**Issue by bradotlin** [f5devcentral/f5-bigip-image-generator#41]
on page AWS Quick Start Guide https://github.com/f5devcentral/f5-bigip-image-generator/tree/master/docs/providers/aws , there are a few links which are 404:

**Create image for AWS using Docker container**
Step 7: Create/upload **config.yaml file**

The config.yaml file link https://github.com/f5devcentral/f5-bigip-image-generator/blob/master/docs/providers/aws/5 gets a 404

based on the Azure page perhaps it should be: https://github.com/f5devcentral/f5-bigip-image-generator/blob/master/README.md#create-config-file

These are wrong too

- Consult the main [ReadMe file here](https://github.com/f5devcentral/f5-bigip-image-generator/blob/master/docs/providers/aws/5) for complete config file details.

-  see the [K14946](https://github.com/f5devcentral/f5-bigip-image-generator/blob/master/docs/providers/aws/4) article.

**Comment by gabetellier** [comment]
Fixed
