### ISSUE TITLE
Setup genisoimage in setup-build-env

### ISSUE THREAD

**Issue by nmenant** [f5devcentral/f5-bigip-image-generator#6]
I used the f5-bigip-image-generator and build-image failed because isoinfo was missing. 

Updating setup-build-env to install this package would make the process smoother

i used Ubuntu 18.04 LTS as requested in the documentation

**Comment by kmaloney** [comment]
We also encountered this issue, and it is being tracked internally with Jira item VECLOUD-798.

This will be fixed in the next release.

**Comment by kmaloney** [comment]
Resolved in v1.2.
